intl: EN: Remove plural s for "information"
devolo/Cockpit-open-frontend pull request #7
Opened 2022-02-02 15:49 UTC by olof-nord

Hello Devolo team!

Usually the usage of the English word "information" is uncountable.

Me reading this message made me assume it was a translation mistake, the Wiktionary [1] entry lists it as _usually_ uncountable. 

With this PR I can only talk for myself, and perhaps if you have a translation team ask them what they say?

btw: many thanks for the recent updates, now I can run the application locally without any problems.

[1] https://en.wiktionary.org/wiki/information

2022-02-02 18:39 UTC, Shutgun requested changes
Nice catch, just two small suggestions.

2022-02-02 18:39 UTC, Shutgun commented on lib/generated/intl/messages_en.dart
> +            "The support information have been created and are now available to you. Please select an action."),
```suggestion
            "The support information has been created and is now available to you. Please select an action."),
```

2022-02-02 18:39 UTC, Shutgun commented on lib/l10n/intl_en.arb
> +  "cockpitSupportInformationBody": "The support information have been created and are now available to you. Please select an action.",
```suggestion
  "cockpitSupportInformationBody": "The support information has been created and is now available to you. Please select an action.",
```

2022-02-03 13:14 UTC, olof-nord commented
Happz to hear positive feedback.
Suggestions added, thanks for the review.

2022-02-03 13:24 UTC, Shutgun approved these changes

2022-02-03 17:18 UTC, olof-nord commented
A quick note regarding merging: "Only those with write access to this repository can merge pull requests.".
If and when this should be merged, the assistance of someone with write access is required.

2022-02-03 18:18 UTC, Shutgun commented
Yeah, it will be merged soon, I just want @Calorine or @julienAhn to have a chance to review it, too.

2022-02-08 14:04 UTC, julienAhn approved these changes
This looks good. Thank you for contributing!

2022-02-08 14:04 UTC, merged